// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AmapAddress {
    "formattedAddress": string;
    "province": string;
    "city": string;
    "district": string;
    "township": string;
    "street": string;
    "number": string;
    "adcode": string;
    "citycode": string;
    "location": string;

    /** Creates a new AmapAddress instance. */
    constructor($$source: Partial<AmapAddress> = {}) {
        if (!("formattedAddress" in $$source)) {
            this["formattedAddress"] = "";
        }
        if (!("province" in $$source)) {
            this["province"] = "";
        }
        if (!("city" in $$source)) {
            this["city"] = "";
        }
        if (!("district" in $$source)) {
            this["district"] = "";
        }
        if (!("township" in $$source)) {
            this["township"] = "";
        }
        if (!("street" in $$source)) {
            this["street"] = "";
        }
        if (!("number" in $$source)) {
            this["number"] = "";
        }
        if (!("adcode" in $$source)) {
            this["adcode"] = "";
        }
        if (!("citycode" in $$source)) {
            this["citycode"] = "";
        }
        if (!("location" in $$source)) {
            this["location"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AmapAddress instance from a string or object.
     */
    static createFrom($$source: any = {}): AmapAddress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AmapAddress($$parsedSource as Partial<AmapAddress>);
    }
}

export class ImageInfo {
    "path": string;
    "name": string;
    "size": number;
    "mimeType": string;
    "width": number;
    "height": number;
    "exif": { [_ in string]?: string };

    /** Creates a new ImageInfo instance. */
    constructor($$source: Partial<ImageInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("exif" in $$source)) {
            this["exif"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageInfo {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("exif" in $$parsedSource) {
            $$parsedSource["exif"] = $$createField6_0($$parsedSource["exif"]);
        }
        return new ImageInfo($$parsedSource as Partial<ImageInfo>);
    }
}

export class LoadedImage {
    "info": ImageInfo | null;
    "dataURL": string;

    /** Creates a new LoadedImage instance. */
    constructor($$source: Partial<LoadedImage> = {}) {
        if (!("info" in $$source)) {
            this["info"] = null;
        }
        if (!("dataURL" in $$source)) {
            this["dataURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadedImage instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadedImage {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField0_0($$parsedSource["info"]);
        }
        return new LoadedImage($$parsedSource as Partial<LoadedImage>);
    }
}

export class SavedImage {
    "path": string;
    "name": string;
    "size": number;

    /** Creates a new SavedImage instance. */
    constructor($$source: Partial<SavedImage> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedImage instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedImage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedImage($$parsedSource as Partial<SavedImage>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ImageInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
